apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
        - name: sql-db-container
          image: mysql:8.1
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: db_name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: db_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: db_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: db_root_password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-service-selector-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-service-selector-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc
