apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: rafaeldemiranda/techchallenge:2.0.3
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: db-service
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: db_name
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tech-challenge
                  key: jwt_secret
